name: blissful_backdrop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.3.0
  path: ^1.9.0
  http: ^1.2.1
  path_provider: ^2.1.2
  html: ^0.15.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.2.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  aptabase_flutter: ^0.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
